### ISSUE TITLE
Can't Find Midi any Midi Devices after multiple uses...

### ISSUE THREAD

**Issue by johnman51** [tsbkelly/Streamdeck-Midibutton#1] opened 2020-03-25 16:01 UTC
Hello,
Thank you very much for creating this useful tool!
Also I made my setup, all working at the beginning...
but after a few uses, it seems that I can't find my midi devices (the choice box is empty)
Did you noticed the same issue? (knowing that I have a lot of usb-midi devices in my setup...)

Kind Regards,
François (France)

**Comment by tsbkelly** [comment] 2020-03-26 14:54
Hey François,

Are you running the latest version (either from the Releases folder, or directly from the Stream Deck plugin store)? I think I've introduced a bug... Will check it out and try and fix it asap.

Cheers,

Tom

**Comment by tsbkelly** [comment] 2020-03-26 15:01
So you could try re-downloading it now from the latest update and tell me if that fixes the problem.

**Comment by johnman51** [comment] 2020-03-26 17:11
Hello Tom!
Thank you for your answer !

I already was running on the last version, but I realized I had two stream deck profiles, so I deleted the unused one, and after reinstalling the stream deck software (not only your plugin…) It worked again!
I’ll get you informed if it happens again…

Anyway, do you think it will possible for you to make possible to assign different midi outputs for each buttons in the future?

Kind regards,
François.

**Comment by davemc615** [comment] 2020-03-26 17:55
Hi Tom,

I am having the same issue as Francois. Have reinstalled Stream Deck and tried all 3 versions of the plugin including direct download within Stream Deck. Seems to be no clear restart or reinstall procedure that will bring back the input/output selections. Thanks.

**Comment by tsbkelly** [comment] 2020-03-26 20:54
Hey François,

Glad it's working again. I've pushed an update to Elgato, and they will hopefully push it to the Stream Deck store soon. Let me know if it happens again. I hadn't planned to make it possible for each button to have a different MIDI port, as that doesn't fit my use-case, but I'll have a look into it and see what's possible.

Dave,

Sorry you're having trouble. I've just pushed a new version to Github that might fix your issue. Let me know if it doesn't.

Cheers,

Tom

**Comment by davemc615** [comment] 2020-03-27 00:19
Hey Tom,

Tried the new version with the same issues. 

Here is a screenshot of the issue. Just does not show a drop-down when clicked. 

Thanks for your work on this. For what it's worth, if it ends up being possible to assign different MIDI ports to each button, that is a functionality I would definitely use. Would also open up this to a lot of versatility. 

Again, very much appreciated. 
![Screen Shot 2020-03-26 at 7 15 44 PM](https://user-images.githubusercontent.com/62717155/77708661-adcea500-6f96-11ea-9379-bf04cc4cc758.png)

**Comment by tsbkelly** [comment] 2020-03-27 09:19
Hi Dave,

Sorry to hear that. Could you do me a favour? Could you try the following, please?

- Turn on "Debug"
- Try selecting "Use Virtual Port" and see if that works (this will at least tell us if the plugin is initialising MIDI correctly)
- De-select "Use Virtual Port" and see if anything changes
- Send me the contents of the log file in "User > Library > Logs > StreamDeck" (the latest log should be called co.uk.clarionmusic.midibutton0.log)
- Send me a screenshot of your Audio/Midi Setup

Good to know multiple MIDI ports would be helpful for you too. Out of interest what's your use-case?

Cheers,

Tom

**Comment by davemc615** [comment] 2020-03-28 18:18
Hey Tom,

-No luck going the virtual port route. 

-Turned on debug and went through the motions, but the log file contained no data. Attaching Stream Deck log here in case it provides any insight. 

-Screenshot of Audio/MIDI below. I made a specific Bus for Stream Deck MIDI for testing purposes. 
[StreamDeck0.log](https://github.com/tsbkelly/Streamdeck-Midibutton/files/4397616/StreamDeck0.log)

-Through further observation, it seems that the input/output selections become available after an undetermined amount of time. I will leave my machine and come back later to the options being there and everything functioning as it should. Verified through MIDI Monitor. If Stream Deck is shut down and restarted, the issue returns on restart. Maybe this helps with some clarity on the issue? 

With regards to use-case, I am a touring audio engineer. I currently utilize MIDI in and out of my console for various control functions, whether it be to control external record software, or bringing in MIDI so that functions can be controlled in the background while I am actively mixing the show. We have a full MIDI network on stage which gathers drum triggers, keyboards, etc which then feeds a few machines running ableton for samples and other sounds. 

We have an operator for that system who currently uses a controller that is no longer in production. The Stream Deck would be quite power for him given it's flexibility. 
![Screen Shot 2020-03-28 at 12 55 32 PM](https://user-images.githubusercontent.com/62717155/77830348-dae59980-70f5-11ea-839a-44aaaac7f5d7.png)


Thanks!

**Comment by tsbkelly** [comment] 2020-03-28 20:07
Hi Dave,

Thanks for sending that through. The plugin is crashing, which is why you're seeing this behaviour - I don't know enough about Elgato's application to debug it, so I'll pass this on to my contact at Elgato. However, it does keep panicking because you have another instance of the Stream Deck application running ("13:05:05.0629          int main(): Another Stream Deck instance is running. Quit!") which might be something to do with it (as I think my plugin won't handle two instances of it trying to run simultaneously very well). Any ideas why you might have another instance running? Might be worth a full uninstall and reinstall.

Thanks for taking me through your use case. Genuine question - is there any reason why you need different MIDI ports? Could you use the same MIDI port and send different messages? It's non-trivial to rewrite the plugin to use different MIDI ports. Not saying I don't want to do it (got to have a project, particularly now)...

Cheers,

Tom

**Comment by johnman51** [comment] 2020-03-28 20:25
﻿Hello Tom!

Like Dave, I discovered that after a short time, all the outputs appears normally... (I have to try a few more reboots to be sure about this... but it appears to work well most of the time here...

About my use of it, it’s absolutely the same as Dave...
I look forward to use it in my studio to control my DIY midi-controlled audio patch but also my digital consol and other things like Ableton live or Midi to cv tools...

Do you think it would be able to make a toggle/release functiin between two values for Midi CC (same options you made for note but for midi CC..)

Kind regards,
François.

Le 28 mars 2020 à 21:07, tsbkelly <notifications@github.com> a écrit :

﻿

Hi Dave,

Thanks for sending that through. The plugin is crashing, which is why you're seeing this behaviour - I don't know enough about Elgato's application to debug it, so I'll pass this on to my contact at Elgato. However, it does keep panicking because you have another instance of the Stream Deck application running ("13:05:05.0629 int main(): Another Stream Deck instance is running. Quit!") which might be something to do with it (as I think my plugin won't handle two instances of it trying to run simultaneously very well). Any ideas why you might have another instance running? Might be worth a full uninstall and reinstall.

Thanks for taking me through your use case. Genuine question - is there any reason why you need different MIDI ports? Could you use the same MIDI port and send different messages? It's non-trivial to rewrite the plugin to use different MIDI ports. Not saying I don't want to do it (got to have a project, particularly now)...

Cheers,

Tom

**Comment by tsbkelly** [comment] 2020-03-31 10:33
Hi both,

Waiting to hear back from my contact about your crashes. In the meantime I've added MIDI Toggle functionality - I'd really appreciate it if you could download the new version and give it a try. If it works well I'll re-write the MIDI Note to have a separate MIDI Note Toggle functionality.

Cheers,

Tom

**Comment by johnman51** [comment] 2020-03-31 16:39
Hey Tom!
These new features appears to work very well on my setup!
You’re on the way to create a USEFULL tool on StreamDeck for MANY PEOPLE...

The great thing would be (in CC mode) to have also a Latch Option.
In my case, I would use it to send some smoke on stage as long as I push the button, That would be an AWESOME feature!

Or like the OSC Remote Plugin on StreamDeck, a fade option (for everything midi) would be a killer feature! (It could be useful for audio or light fades under the fingers during shows !!!)

Anyway, I know this is a hard work to develop but, just in case, I prefer to share my wishes, we never know… ;-)

Kind Regards,
François.

**Comment by tsbkelly** [comment] 2020-03-31 17:05
Hey François,

That's great to know that the new functions work well, and thanks for the feedback!

Shouldn't be too hard to add a latch feature for CC, and I'll look into a fade function for CC as well.

Cheers,

Tom

**Comment by davemc615** [comment] 2020-03-31 17:36
Hey Tom,

-Not sure why it though there were two instances running. The OS gave no indication of such either in the foreground or background. That said, the new version with a few full reboots seem to have negated that issue. MIDI ports showed up immediately on launch this time around. As I go through testing, Ill let you know if things stay stable. 

-Regarding the need for additional MIDI ports per button: We have so much MIDI information flowing in all directions, that we use every channel. As we use it in a live show setting, much of it is critical information that needs to be bulletproof. As such, we dedicated specific ports for individual data based on the use. This helps keep potential for crosstalk down, which has happened in the past. We also utilize a program MidiPipe to help filter the flow of data as well. 

-Again, seriously thank you for this. Fingers crossed, that when this craziness settles down our tour will go off as planned. Looking forward to integrating this into the rig.

**Comment by tsbkelly** [comment] 2020-04-07 12:40
Hi both,

I've uploaded a new version with a MIDI CC toggle and fade option. Any comments gratefully received. Going to implement a latch for MIDI CC too.

Cheers,

Tom

**Comment by johnman51** [comment] 2020-04-07 15:03
Hi Tom!
I couldn't find the fade option, are you sure fades was uploaded on your last release?

Kind regards,
François.

**Comment by tsbkelly** [comment] 2020-04-07 15:13
That's because I stupidly didn't push the changes to Github... Try again now?

**Comment by johnman51** [comment] 2020-04-07 18:38
Hi Tom!

So, I tried, and it work quite well!
I hade a few non-working moments during settings but after reloading both stream deck and DMXIS software for exemple, It seems to be ok...
I’ll try again more cases tomorrow and I’ll let you informed!

Do you thing a latch function with fade would be possible? (For a smooth add of smoke on stage during the button is pressed but with a smooth in and out for the smoke machine.::) —-> an awesome function the would avoid a lot of cute settings in many softwares... ;-)

Kind regards,
François.

Le 7 avr. 2020 à 17:13, tsbkelly <notifications@github.com> a écrit :

﻿

That's because I stupidly didn't push the changes to Github... Try again now?

**Comment by tsbkelly** [comment] 2020-04-07 18:44
Hi François,

Good to know it's working initially. You should be able to achieve what you're describing using the MIDI CC Toggle action - set up the action with a fade, and then toggle between the two states. If you set your smoke machine to respond to a MIDI CC of 127 for on (for example) and set the two midi values to be 0 and 127 you can then press the button for a fade in, latch and a fade out. Or did you mean something else?

Cheers,

Tom

**Comment by johnman51** [comment] 2020-04-08 10:33
Hi Tom !

My mistake… It works as a latch button, but what I wish would be a momentary function also (very useful):

———————————————————————————————
▣         when I press & hold the button it would engage a -fade in- to 127 and stay at this value only if I hold the button,
———————————————————————————————
□          then, if I release the button, it would fade out to 0.
———————————————————————————————


I hope it won’t be to hard for you to code It!
My English is not perfect sorry, :-).

Again, THANK YOU VERY MUCH !
Kind Regards,
François.

**Comment by davemc615** [comment] 2020-04-08 17:24
Hey Tom,

Seems that the crash is back. Tried installing the previous version and happening with that as well. 

As before, no log from MIDI Button, but attached is the Log from StreamDeck. Did not see an indicator of second instance running in this one, but it does seem that the plugin is crashing. 

Was your contact able to provide any insight there? 

Thanks!

[StreamDeck0.log](https://github.com/tsbkelly/Streamdeck-Midibutton/files/4451896/StreamDeck0.log)

**Comment by tsbkelly** [comment] 2020-04-08 18:08
Hi Dave,

The plugin is crashing because of a segfault - my contact couldn't give me any more information than that. He did, however, say that because you're running High Sierra it's possible that some of the plugin base code (which is only certified for Mojave, I believe) might be causing the issue. I'm going to build a High Sierra VM and try it out in that, so will let you know how I get on.

Cheers,

Tom

**Comment by davemc615** [comment] 2020-04-08 18:18
Tom,

Thanks for the info here.

Interesting that it may be a OS related issue. I’ve been holding out on moving up due to my machine’s age and some of the legacy software I run.

Curious to see if that fixes it.



Dave McMullin
615.715.5955

**Comment by tsbkelly** [comment] 2020-04-12 09:19
Hi both,

So I've re-written how the plugin initialises MIDI ports, and it's working well on my system. Would you mind trying it on yours?

https://www.dropbox.com/s/0uuhleknpqldz54/co.uk.clarionmusic.midibutton.streamDeckPlugin?dl=0

François, I've added in the functionality you asked for - let me know if it works, and if it works as you expected/hoped!

The more testing you can do the more I'd appreciate it.

Cheers,

Tom

**Comment by johnman51** [comment] 2020-04-12 13:28
Hi Tom!
Step by step, we’re almost there!!!

Your plugin is becoming a INCREDIBLE tool for every one!!! 
I already have new ideas using your the new features you implemented!
It’s making my life so easier !!!!

After programming everything and restarting all of my stuff safely, I had no troubles for the moment.
GREEEAAAT JOB !!!
I think we will ear about your job in many DAW users websites in a near future.

Do you think it would also be possible to get a similar option as the CC toggle but for notes at aim to name to states off the butons (like On & Off names) ?

My new request would be to be able to set more than on note on the same midi button, that would be great !!!

Kind regards,
François.

**Comment by davemc615** [comment] 2020-04-14 18:05
Hey Tom,

Everything appears to be working 100% on my end. 

Along with Francois, is it possible for the CC Toggle to have different displays per state? 

Is the possibility of different MIDI channel per button still a possibility? 

Thanks again for all of this. Will keep testing this week and let you know how things go. 

Hope you are staying healthy and safe.

**Comment by tsbkelly** [comment] 2020-04-15 09:36
Hi both,

Really glad that this seems to have fixed the problem for you both. I've added a Note Toggle action, so you can toggle between note on and off, which I'll send to you both shortly. Dave, could you explain what you mean? You can give the CC toggle (and the note toggle, when you have it) different displays by clicking the little arrow in the Property Inspector and choosing an icon file for each state. Or did you mean something else?

Cheers,

Tom

**Comment by turtleboy13** [comment] 2020-04-26 04:57
Greetings!  I've been working with Stream Deck a few days and haven't had success with sending MIDI.  I'm running Logic on Mojave.  Logic sees key commands, but no MIDI commands. (I'm trying to trigger notes in the lower octaves used for sound changes in libraries like Native Instruments Kontakt).  Stream Deck support had me update to your 1.04 version.  Still no luck.  My buddy checked also, who is also a professional keyboardist/composer- he had the same issues.  He also brought this up: "In looking through Console logs I stumbled on a handful of crashes related to that MIDI extension.  In fact, I need to figure out how to uninstall it because now my computer takes longer to start up!".  I appreciate any feedback- Kurt

**Comment by tsbkelly** [comment] 2020-04-26 08:00
Hi Kurt,

Sorry to hear you're having issues. Your use case is the same as mine, and is why I developed the plugin. Could you do a few things for me, please? Could you try downloading the plugin from the Dropbox link above and installing that version? Could you then switch on debugging in the Setup part of the property inspector, and then send me the StreamDeck0.log and co.uk.clarionmusic.midibutton0.log from Mac HD > Users > YOURUSERNAME > Library > Logs > StreamDeck? That'll give me an idea of what's going wrong. If your composer friend could do the same that would be great. The plugin is entirely self-contained (it doesn't install any drivers or extensions) so if you want to uninstall it you do that from the Stream Deck software, and that will remove it completely.

Thanks,

Tom

**Comment by turtleboy13** [comment] 2020-04-26 12:50
Thanks- I will work on this. I di not see the Dropbox link...

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by benbridts** [comment] 2020-04-26 13:28
Hi Tom,

I think I have the same issue, unfortunately that dropbox link does not work anymore. Could you upload it again?

Kind regards,
Ben

**Comment by tsbkelly** [comment] 2020-04-26 15:29
Hi Kurt, and hi Ben,

Sorry about that - here's a new Dropbox link:

https://www.dropbox.com/s/pfwqx5ti9cgmz3s/co.uk.clarionmusic.midibutton.streamDeckPlugin?dl=0

Ben, if you could do the same debugging as Kurt and send me the logs I'd really appreciate it.

Cheers,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 05:31
I’ve updated the dropbox software and that hasn’t changed anything.  
You’ll have to be more specific for me- where do I find the property inspector, etc.?
Thanks-

Kurt Heinecke
KH Studios, Inc.
kurt@khstudios.biz
www.khstudios.biz
615.480.4013

**Comment by tsbkelly** [comment] 2020-04-27 07:41
Hi Kurt,

The Property Inspector is in the Stream Deck software - click on the Stream Deck icon at the top of the screen, select "Configure Stream Deck" and the Stream Deck configuration software will then appear. If you then select whichever MIDI button plugin you'd like to use (I'd suggest MIDI Note for you) and drag it to an empty space the Property Inspector will then appear at the bottom of the software. The very last option is "Setup" - expand this by clicking the arrow, and you'll see an option for "Debug" - turn that on and then send me the logs as described above.

Thanks,

Tom

**Comment by benbridts** [comment] 2020-04-27 08:51
Hi Tom,

I hope this helps:

[co.uk.clarionmusic.midibutton0.log](https://github.com/tsbkelly/Streamdeck-Midibutton/files/4538459/co.uk.clarionmusic.midibutton0.log)
[StreamDeck0.log](https://github.com/tsbkelly/Streamdeck-Midibutton/files/4538460/StreamDeck0.log)

Kind regards,
Ben

**Comment by tsbkelly** [comment] 2020-04-27 09:34
Hi Ben,

Thanks for the logs. Could you try trashing the folder macOS HD > Users > YOURUSERNAME > Library > Application Support > Plugins > uk.co.clarionmusic.midibutton.sdPlugin, reinstall from the above Dropbox link, and then resend the log files, please? Could you also delete and recreate any midibutton actions you may have set up? There's some funky stuff going on and it would be good to try and eliminate some possible causes.

Thanks,

Tom

**Comment by benbridts** [comment] 2020-04-27 10:46
Hi Tom,

I removed the plugin from within Elgato, It seems to have the same effect:

```
~$ ls Library/Application\ Support/com.elgato.StreamDeck/Plugins/
com.animapix.oscremote.sdPlugin          com.elgato.philips-hue.sdPlugin
com.elgato.controlcenter.sdPlugin        com.nicollasr.streamdeckvsc.mac.sdPlugin

~$ grep -R uk.co.clarionmusic Library/Application\ Support/com.elgato.StreamDeck/ProfilesV2/
[no output]
```

After installation:

```
~$ ls Library/Application\ Support/com.elgato.StreamDeck/Plugins/
co.uk.clarionmusic.midibutton.sdPlugin   com.elgato.philips-hue.sdPlugin
com.animapix.oscremote.sdPlugin          com.nicollasr.streamdeckvsc.mac.sdPlugin
com.elgato.controlcenter.sdPlugin

~$ grep -R uk.co.clarionmusic Library/Application\ Support/com.elgato.StreamDeck/ProfilesV2/
/Users/ben/Library/Application Support/com.elgato.StreamDeck/ProfilesV2//8AC265C2-EB1C-4870-8622-8CEE241EB2EE.sdProfile/manifest.json: [full output skipped]

~ cat Library/Application\ Support/com.elgato.StreamDeck/ProfilesV2/8AC265C2-EB1C-4870-8622-8CEE241EB2EE.sdProfile/manifest.json | jq '.Actions["0,1"]'
{
  "Name": "MIDI Note",
  "Settings": null,
  "State": 0,
  "States": [
    {
      "FFamily": "",
      "FSize": "",
      "FStyle": "",
      "FUnderline": "",
      "Image": "",
      "Title": "",
      "TitleAlignment": "",
      "TitleColor": "",
      "TitleShow": ""
    }
  ],
  "UUID": "uk.co.clarionmusic.midibutton.noteon"
}
```

Thanks for looking into this.

[co.uk.clarionmusic.midibutton0.log](https://github.com/tsbkelly/Streamdeck-Midibutton/files/4539108/co.uk.clarionmusic.midibutton0.log)
[StreamDeck0.log](https://github.com/tsbkelly/Streamdeck-Midibutton/files/4539109/StreamDeck0.log)


Kind regards,
Ben

**Comment by tsbkelly** [comment] 2020-04-27 13:54
Hi Ben,

I've passed this on to Elgato, as the plugin is terminating due to a SIGHUP (which I'm assuming is the websocket terminating), rather than in my code. As soon as they come back to me I'll let you know what they say.

Cheers,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 14:36
Thanks!

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by turtleboy13** [comment] 2020-04-27 15:02
Do you still want to see logs from me, or wait until update from Elgato?

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by tsbkelly** [comment] 2020-04-27 16:02
Kurt,

Yes please, to see whether you're having the same issue as Ben.

Thanks,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 16:26
I’ll work on that ASAP. 

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by turtleboy13** [comment] 2020-04-27 16:48
This is the only related log I can find-




I also grabbed this- not sure if input/output makes a difference. 

I can confirm, like before, I’m seeing no actions or messages (no exclamation mark) from the midi note buttons, but am seeing a key command work within logic.





Kurt Heinecke
KH Studios, Inc.
kurt@khstudios.biz
www.khstudios.biz
615.480.4013

**Comment by tsbkelly** [comment] 2020-04-27 17:02
Hi Kurt,

Your message doesn't have anything attached or inline - can you resend, please?

Thanks,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 17:16
This is the only related log I can find-




I also grabbed this- not sure if input/output makes a difference. 

I can confirm, like before, I’m seeing no actions or messages (no exclamation mark) from the midi note buttons, but am seeing a key command work within logic.





Kurt Heinecke
KH Studios, Inc.
kurt@khstudios.biz <mailto:kurt@khstudios.biz>
www.khstudios.biz
615.480.4013

**Comment by turtleboy13** [comment] 2020-04-27 17:16
Just sent again- you should see a .diag message, and a screen shot.

Kurt Heinecke
KH Studios, Inc.
kurt@khstudios.biz
www.khstudios.biz
615.480.4013

**Comment by tsbkelly** [comment] 2020-04-27 17:51
Hi Kurt,

I think you're replying to the email, and Github is stripping your attachments out - can you try replying on the Github page, rather than through email?

Thanks,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 17:56
👍

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by turtleboy13** [comment] 2020-04-27 18:00
Here you go:

Date/Time:       2020-04-27 11:37:39 -0500
OS Version:      Mac OS X 10.14.6 (Build 18G95)
Architecture:    x86_64h
Report Version:  28
Incident Identifier: CFB8BE08-E5BE-4B4B-996C-82FA82CF25C3

Data Source:     Microstackshots
Shared Cache:    0x17e32000 22DED86B-7D9B-35E5-BB51-8B5DB2472AB9

Command:         midibutton
Path:            /Users/khmini/Library/Application Support/com.elgato.StreamDeck/Plugins/co.uk.clarionmusic.midibutton.sdPlugin/midibutton
Version:         ??? (???)
PID:             929

Event:           wakeups
Action taken:    none
Wakeups:         45001 wakeups over the last 53 seconds (852 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:   45000
Limit duration:  300s
Wakeups caused:  45001
Duration:        0.00s
Steps:           1

Hardware model:  Macmini8,1
Active cpus:     12


Heaviest stack for the target process:
  1  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff6f92c40d]
  1  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff6f930249]
  1  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff6f92d2eb]
  1  void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CallBackTimer::start(int, std::__1::function<void ()>)::$_0> >(void*) + 118 (midibutton + 1165974) [0x108de9a96]
  1  void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CallBackTimer::start(int, std::__1::function<void ()>)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CallBackTimer::start(int, std::__1::function<void ()>)::$_0>&, std::__1::__tuple_indices<>) + 37 (midibutton + 1168261) [0x108dea385]
  1  decltype(std::__1::forward<CallBackTimer::start(int, std::__1::function<void ()>)::$_0>(fp)()) std::__1::__invoke<CallBackTimer::start(int, std::__1::function<void ()>)::$_0>(CallBackTimer::start(int, std::__1::function<void ()>)::$_0&&) + 29 (midibutton + 1168413) [0x108dea41d]
  1  CallBackTimer::start(int, std::__1::function<void ()>)::$_0::operator()() const + 106 (midibutton + 1168586) [0x108dea4ca]
  1  void std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) + 175 (midibutton + 1168783) [0x108dea58f]
  1  std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73 (libc++.1.dylib + 48580) [0x7fff6c96edc4]
  1  nanosleep + 91 (libsystem_c.dylib + 501928) [0x7fff6f7fd8a8]
  1  clock_get_time + 85 (libsystem_kernel.dylib + 20574) [0x7fff6f87205e]
  1  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff6f86e22a]


Powerstats for:  midibutton [929]
UUID:            4FFCE614-364F-368C-8D82-B598DA8805D6
Path:            /Users/khmini/Library/Application Support/com.elgato.StreamDeck/Plugins/co.uk.clarionmusic.midibutton.sdPlugin/midibutton
Architecture:    x86_64
Parent:          UNKNOWN [921]
Responsible:     UNKNOWN [921]
UID:             501
Footprint:       1124 KB
Start time:      2020-04-27 11:37:39 -0500
End time:        2020-04-27 11:37:39 -0500
Num samples:     1 (100%)
Primary state:   1 samples Non-Frontmost App, Non-Suppressed, Kernel mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:   0 samples Idle, 1 samples Active
Power Source:    0 samples on Battery, 1 samples on AC
  1  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff6f92c40d]
    1  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff6f930249]
      1  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff6f92d2eb]
        1  void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CallBackTimer::start(int, std::__1::function<void ()>)::$_0> >(void*) + 118 (midibutton + 1165974) [0x108de9a96]
          1  void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CallBackTimer::start(int, std::__1::function<void ()>)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CallBackTimer::start(int, std::__1::function<void ()>)::$_0>&, std::__1::__tuple_indices<>) + 37 (midibutton + 1168261) [0x108dea385]
            1  decltype(std::__1::forward<CallBackTimer::start(int, std::__1::function<void ()>)::$_0>(fp)()) std::__1::__invoke<CallBackTimer::start(int, std::__1::function<void ()>)::$_0>(CallBackTimer::start(int, std::__1::function<void ()>)::$_0&&) + 29 (midibutton + 1168413) [0x108dea41d]
              1  CallBackTimer::start(int, std::__1::function<void ()>)::$_0::operator()() const + 106 (midibutton + 1168586) [0x108dea4ca]
                1  void std::__1::this_thread::sleep_for<long long, std::__1::ratio<1l, 1000l> >(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) + 175 (midibutton + 1168783) [0x108dea58f]
                  1  std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73 (libc++.1.dylib + 48580) [0x7fff6c96edc4]
                    1  nanosleep + 91 (libsystem_c.dylib + 501928) [0x7fff6f7fd8a8]
                      1  clock_get_time + 85 (libsystem_kernel.dylib + 20574) [0x7fff6f87205e]
                        1  mach_msg_trap + 10 (libsystem_kernel.dylib + 4650) [0x7fff6f86e22a]

  Binary Images:
           0x108ccd000 -        0x108e2efff  midibutton (0)                      <4FFCE614-364F-368C-8D82-B598DA8805D6>  /Users/khmini/Library/Application Support/com.elgato.StreamDeck/Plugins/co.uk.clarionmusic.midibutton.sdPlugin/midibutton
        0x7fff6c963000 -     0x7fff6c9b6fff  libc++.1.dylib (400.9.4)            <9A60A190-6C34-339F-BB3D-AACE942009A4>  /usr/lib/libc++.1.dylib
        0x7fff6f783000 -     0x7fff6f80afff  libsystem_c.dylib (1272.250.1)      <7EDACF78-2FA3-35B8-B051-D70475A35117>  /usr/lib/system/libsystem_c.dylib
        0x7fff6f86d000 -     0x7fff6f895fff  libsystem_kernel.dylib (4903.271.2) <EA204E3C-870B-30DD-B4AF-D1BB66420D14>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff6f92a000 -     0x7fff6f934fff  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7>  /usr/lib/system/libsystem_pthread.dylib

**Comment by tsbkelly** [comment] 2020-04-27 18:31
Hi Kurt,

Are there any logs at all in Mac HD > Users > YOURUSERNAME > Library > Logs > StreamDeck ? If so, could you send them to me please? Could you also send a screenshot of the Stream Deck configuration application?

Thanks,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 19:43
That is all I found, and that was under library under Mac hard drive. I am not seeing any library‘s under my user name.

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by turtleboy13** [comment] 2020-04-27 19:45
![Screen Shot 2020-04-27 at 2 44 04 PM](https://user-images.githubusercontent.com/64344950/80413828-af410500-8895-11ea-8537-29a78c2c99e8.png)
![Screen Shot 2020-04-27 at 11 41 35 AM 2](https://user-images.githubusercontent.com/64344950/80413850-b7994000-8895-11ea-831e-2f92c2a12b95.png)

**Comment by tsbkelly** [comment] 2020-04-27 20:11
Hi Kurt,

Follow these instructions to access the user library - https://helpx.adobe.com/uk/x-productkb/global/access-hidden-user-library-files.html. Could you try using the Virtual Port and see whether that works in Logic? You may have to enable it as an input in Logic Pro X > Preferences > MIDI > Input.

Thanks,

Tom

**Comment by turtleboy13** [comment] 2020-04-27 20:42
I will try both of those. May be a bit before I get to that. 

Kurt Heinecke
KH Studios, Inc. 
www.khstudios.biz
kurt@khstudios.biz
615.480.4013

**Comment by turtleboy13** [comment] 2020-05-01 07:32
It's working!  Turning on "use virtual port" did the trick.  I didn't have to adjust anything in Logic, though I did see a note that it was seeing it as a MIDI input.

**Comment by tsbkelly** [comment] 2020-05-01 09:48
Great to know, Kurt. I'm going to close this issue now as it's got slightly off track. Ben, if and when Elgato get back to me I'll send you a message.

Thanks,

Tom

**Closed as completed by tsbkelly** 2020-05-01 09:48 UTC
